### ISSUE TITLE
AttributeError: 'module' object has no attribute '_base'

### ISSUE THREAD

**Issue by Lz1y** [repoog/GitPrey#16]
lzy@47:~/GitPrey$ python GitPrey.py
Traceback (most recent call last):
  File "GitPrey.py", line 12, in <module>
    from bs4 import BeautifulSoup
  File "/usr/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

**Comment by Lz1y** [comment]
sudo pip install --upgrade html5lib==1.0b8
